# Site settings
title: Slatestarcodex articles by popularity
description: > # this means to ignore newlines until "baseurl:"
        Slate start codex is difficult to navigate without knowing which
        articles are best-rated
baseurl: /slatestarcodexfbsharecount
url: "http://afiodorov.github.io/slatestarcodexfbsharecount/"
github_username:  afiodorov

# Build settings
markdown: kramdown
